### ISSUE TITLE
你好，swagger-ui页面显示为空

### ISSUE THREAD

**Issue by iwangjie** [snowxwolf/boot#3]
![image](https://user-images.githubusercontent.com/23075587/40985000-b57c2608-6915-11e8-85c5-82ecc65b5100.png)
当我访问http://localhost:8082/swagger-ui.html  显示的页面，请问是什么原因呢

**Comment by windflowerly** [comment]
是啊。我也遇到这个问题了

**Comment by snowxwolf** [comment]
多谢关注，已修复。
